name: stokip
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    #packages
  cupertino_icons: ^1.0.2
  #state management
  flutter_bloc: ^8.1.3
  #flutter
  equatable: ^2.0.5
  image_picker: ^1.0.4
  #google
  json_annotation: ^4.8.1
  #cache
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  #flchart
  fl_chart: ^0.63.0
  #dart
  easy_localization: ^3.0.3

  very_good_analysis: ^5.1.0
  #vb 10 ;)
  kartal: ^3.4.2
  image_cropper: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #google
  json_serializable: ^6.7.1
  #dart
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like ts:
  assets:
    - assets/translations/
    - assets/pngs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
